### ISSUE TITLE
[SOLVED] setup failed on newer macos i.e. 10.14 (mojave)

### ISSUE THREAD

**Issue by pangwong** [shunsukeaihara/pydtw#3]
if you are newer macos user, you may encounter error like this when using pip install,
```shell
pydtw/dtw.cpp:584:10: fatal error: 'ios' file not found
#include "ios"
         ^~~~~
2 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1
```
 the solution is to add two line in setup.py after imports
```python
import os 
os.environ['MACOSX_DEPLOYMENT_TARGET'] = '10.9'
```

reference :
https://github.com/pandas-dev/pandas/issues/23424#issuecomment-446393981

**Comment by shunsukeaihara** [comment]
fix on this commit 5263f87283a8890aacb2e1d7aaa9266635836723
