### ISSUE TITLE
Possible bug?

### ISSUE THREAD

**Issue by Tahlor** [shunsukeaihara/pydtw#7]
```
x1 = np.array([1,2.0,3])
x2 = np.array([1,1.2,3])
dist, cost, a, b = dtw.dtw1d(x1, x2, )
print(a)
print(b)
```
returns 
[0, 0, 1, 2]
[0, 0, 1, 2]

Shouldn't this be:
[0, 1, 2] 
[0, 1, 2]

Using pydtw 2.0.2, Python 3.8.1, numpy 1.18.1.

**Comment by Tahlor** [comment]
Another one:

```
x1 = np.array([1,2.9,2.9,3])
x2 = np.array([1.1,1.2,1.4,3])
dist, cost, a, b = dtw.dtw1d(x1, x2, )

```
[0, 0, 1, 2, 3]
[0, 2, 3, 3, 3] <- 1 index does not appear

I believe this should be:
[0 0 0 1 2 3]
[0 1 2 3 3 3]

**Comment by Tahlor** [comment]
PR #8 resolves these issues

**Comment by Tahlor** [comment]
The cost for the first example is reported to be `0` and the second example `inf`. This has been fixed in 
4443c1a.

**Comment by shunsukeaihara** [comment]
#8 Thanks.
